POSTGRES_DATABASE_ENV_VAR = "POSTGRES_DATABASE_URL"

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%f"

BULK_IMPORT_LIMIT = 1000

ERRORS_TABLE_NAME = "parsing_errors"
COMMENTS_TABLE_NAME = "comments"
POSTS_TABLE_NAME = "posts"
USERS_TABLE_NAME = "users"
