version: "3.9"

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile-API
    environment:
      - POSTGRES_DATABASE_URL=postgresql://admin:admin@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin

  app:
    image: stacks-importer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DATABASE_URL=postgresql://admin:admin@db:5432/postgres
    depends_on:
      - db
      - api
      - pgadmin
